### ISSUE TITLE
How to permanently change the default download folder

### ISSUE THREAD

**Issue by Navid906** [varunpanchal283/Re-Anime#1]
Hay man I Wana change my download folder of re-anime that are currently default to "./home/pi/Desktop/anime" from the cli.py . what should I do? Plz man help me 

I'm really appreciate your work. 
Regards.

**Comment by varunpanchal283** [comment]
well there is a temporary option use '-dir' to change your download directory
eg: `re-anime -d <url> -ep <> -dir <valid-path>`
There is no permanent option for changing download directory but if you wanna change the default directory in cli.py, you need to change 2 lines
1st is at 40th line inside 'parse' function change 'downdir' variable to a string valid path inside a list eg: ["D:/Anime"] 
2nd is at 153th line inside 'dir' function change the 'temp' variable to a string valid path   eg: "D:/Anime"
Hope this would help you

**Comment by Navid906** [comment]
> well there is a temporary option use '-dir' to change your download directory
> eg: `re-anime -d <url> -ep <> -dir <valid-path>`
> There is no permanent option for changing download directory but if you wanna change the default directory in cli.py, you need to change 2 lines
> 1st is at 40th line inside 'parse' function change 'downdir' variable to a string valid path inside a list eg: ["D:/Anime"]
> 2nd is at 153th line inside 'dir' function change the 'temp' variable to a string valid path eg: "D:/Anime"
> Hope this would help you

It says path not found

**Comment by Navid906** [comment]
![Uploading IMG_20210614_132612.jpg…]()

**Comment by varunpanchal283** [comment]
> 
> 
> > well there is a temporary option use '-dir' to change your download directory
> > eg: `re-anime -d <url> -ep <> -dir <valid-path>`
> > There is no permanent option for changing download directory but if you wanna change the default directory in cli.py, you need to change 2 lines
> > 1st is at 40th line inside 'parse' function change 'downdir' variable to a string valid path inside a list eg: ["D:/Anime"]
> > 2nd is at 153th line inside 'dir' function change the 'temp' variable to a string valid path eg: "D:/Anime"
> > Hope this would help you
> 
> It says path not found

well try out the temporary option using `-dir ` to mention your download directory, i will soon add this option of changing the default download directory permanently in the next update

**Comment by varunpanchal283** [comment]
> 
> 
> Hay man I Wana change my download folder of re-anime that are currently default to "./home/pi/Desktop/anime" from the cli.py . what should I do? Plz man help me
> 
> I'm really appreciate your work.
> Regards.

you can now change it please try to update re-anime to version 0.2.4 i have included the feature of changing the default download directory permanently 
`re-anime -changedir "path" ` will change your default directory permanently.
